app = "reits-monitor"
primary_region = "hkg"

[build]
  builder = "node"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
